# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [9]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [10]:
# needed nothing
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
# needed answer for show config
print(np.__version__)
np.show_config()

1.22.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/ericjenvey/opt/miniconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/ericjenvey/opt/miniconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/ericjenvey/opt/miniconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/ericjenvey/opt/miniconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = ASIMDHP
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
# needed answer
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [16]:
# needed answer 
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [17]:
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [18]:
# needed nothing
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [20]:
# needed nothing
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [23]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [24]:
# needed nothing
me = np.arange(10,50)
print(me)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [28]:
# needed nothing
me = np.arange(10,50)
reverse_me = reversed(me)
print(list(reverse_me))

[49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [30]:
# needed nothing
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [35]:
# needed hint
me = np.array([1,2,0,0,4,0])

np.nonzero(me)

(array([0, 1, 4]),)

In [34]:
hint(10)

hint: np.nonzero


#### 11. Create a 3x3 identity matrix (★☆☆)

In [36]:
# needed nothing, but used identity instead of eye
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
answer(11)

Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [47]:
# needed hint, but used random sample rather than random
print(np.random.random_sample(27).reshape(3,3,3))

[[[0.82068543 0.22284205 0.2322809 ]
  [0.80309605 0.22105789 0.22825852]
  [0.84759164 0.49387637 0.8294829 ]]

 [[0.89551192 0.70035917 0.46774491]
  [0.7016806  0.12216577 0.87138025]
  [0.51865747 0.00996096 0.20568983]]

 [[0.35688634 0.12870895 0.06852716]
  [0.71932453 0.02054385 0.16071145]
  [0.75082834 0.43680997 0.34976044]]]


In [48]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [54]:
# needed hint to know the correct min/max command. Used np.min and np.max rather than array.min/array.max
arr = np.random.random((10,10))
print(np.min(arr))
print(np.max(arr))

0.00788283714831084
0.9913683379952036
0.00788283714831084
0.9913683379952036


In [53]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [59]:
# Needed nothing
z = np.random.random(30)
print(z)
print(z.mean())

[0.95996181 0.98908744 0.16081866 0.03693271 0.14330212 0.86178006
 0.64277143 0.37570986 0.88591337 0.04552344 0.48635163 0.24554779
 0.38134469 0.72671251 0.5870735  0.8613808  0.2605747  0.44705033
 0.05386439 0.25047005 0.0047998  0.05507456 0.85560374 0.11970829
 0.70664994 0.72642937 0.2551538  0.39550341 0.67677645 0.50322488]
0.45670318506159785


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [69]:
# Needed hint only, to find slicing strategy
z = np.ones(9).reshape(3,3)
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [70]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [73]:
# Didn't need anything, but, the np.pad method is more concise, AND the slicing could be 
# more efficiently coded using []
z = np.random.random(36).reshape(6,6)
z[0,:] = 0
z[: ,0] = 0
z[-1,:] = 0
z[:, -1] = 0
print(z)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.24117948 0.75312679 0.14555435 0.52419078 0.        ]
 [0.         0.21933611 0.16977913 0.13919442 0.18052109 0.        ]
 [0.         0.87090778 0.2401715  0.36249563 0.04401026 0.        ]
 [0.         0.27093848 0.17337045 0.73885181 0.21545669 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [75]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [81]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [86]:
# Didn't need answer, consulted numpy documentation for np.diag command (rather than using np.eye, which is possible here as well)
z = np.diag(np.array([1,2,3,4]), k = -1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [92]:
# Needed answer. Slicing strategy
z = np.zeros((8,8))
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [90]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [103]:
# Needed answer for np.unravel_index
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


In [105]:
z = np.ones((6,7,8))
z[1,5,3] = 100
print(z)

[[[  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]]

 [[  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1. 100.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]]

 [[  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.]]

 [[  1.   1.   1.   1.   1.   1.   1.   1.]
  [  1.   1.   1.   1.   1

In [100]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [113]:
# Needed answer
np.tile(np.array([[0,1], [1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [119]:
# Didn't need anything, but used array.mean, rather than np.mean
z = np.arange(64).reshape(8,8) 
(z - np.mean(z)) / np.std(z)

array([[-1.70519568, -1.65106248, -1.59692929, -1.54279609, -1.4886629 ,
        -1.4345297 , -1.3803965 , -1.32626331],
       [-1.27213011, -1.21799691, -1.16386372, -1.10973052, -1.05559733,
        -1.00146413, -0.94733093, -0.89319774],
       [-0.83906454, -0.78493134, -0.73079815, -0.67666495, -0.62253176,
        -0.56839856, -0.51426536, -0.46013217],
       [-0.40599897, -0.35186578, -0.29773258, -0.24359938, -0.18946619,
        -0.13533299, -0.08119979, -0.0270666 ],
       [ 0.0270666 ,  0.08119979,  0.13533299,  0.18946619,  0.24359938,
         0.29773258,  0.35186578,  0.40599897],
       [ 0.46013217,  0.51426536,  0.56839856,  0.62253176,  0.67666495,
         0.73079815,  0.78493134,  0.83906454],
       [ 0.89319774,  0.94733093,  1.00146413,  1.05559733,  1.10973052,
         1.16386372,  1.21799691,  1.27213011],
       [ 1.32626331,  1.3803965 ,  1.4345297 ,  1.4886629 ,  1.54279609,
         1.59692929,  1.65106248,  1.70519568]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [124]:
# Needed answer
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [127]:
# Needed to research numpy matrix multiplication methods
# matmul works, as does np.dot, as does the "at" symbol
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)

print(a)
print(b)

np.matmul(a,b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [128]:
answer(24)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


In [131]:
a @ b

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [138]:
# Needed answer, but it was simply a slicing with multiple conditions
z = np.arange(10)
z[(3 < z) & (z < 8)] *= -1
print(z)


[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [136]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [13]:
# Unclear, all?

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [17]:
# NAN
# 0
# Array with 0 as the single value

array([0.])

#### 29. How to round away from zero a float array ? (★☆☆)

In [22]:
# Needed answer. Copysign copies the signs from one array to another, np.where is an ifelse for numpy arrays
Z = np.random.uniform(-10, +10, 10)
print(Z)
print(np.where(Z > 0, np.ceil(Z), np.floor(Z)))

[ 5.3671053  -7.61407163 -3.04784499  8.06504896  7.68506305 -5.96291044
 -2.39758427  3.8878343   4.80131137  1.62481751]
[ 6. -8. -4.  9.  8. -6. -3.  4.  5.  2.]


In [34]:
y = np.array([-1])

In [35]:
print(np.copysign(np.ceil(np.abs(Z)), y))

[-6. -8. -4. -9. -8. -6. -3. -4. -5. -2.]


In [21]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [45]:
# Needed answer to get intersect1d command. a==b will pull the matching indices, but not values. 
a = np.ceil(np.random.uniform(0, 10, 10))
b = np.ceil(np.random.uniform(0,10,10))

print(a)
print(b)

a==b

[7. 5. 3. 3. 9. 9. 3. 4. 1. 3.]
[ 5. 10.  1.  9.  8.  8.  9.  2.  4.  5.]


array([False, False, False, False, False, False, False, False, False,
       False])

In [43]:
np.intersect1d(a,b)

array([1., 4., 5., 7., 8., 9.])

In [41]:
answer(30)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [46]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [49]:
# np.sqrt returns nan, emath.sqrt properly returns an imaginary number
np.emath.sqrt(-1)

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [62]:
# Needed answer for the date commands
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today') 
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(tomorrow)
print(today)

2022-08-19
2022-08-21
2022-08-20


In [61]:
answer(33)

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [71]:
# Needed answer to understand how datetime64 works. Can use subscript to generate ranges across months, years, days, times, etc.
np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [67]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [72]:
# Needed answer to understand the "out" argument. Obviously can do the calculation as below, but will create a copy
a = np.ceil(np.random.uniform(0, 10, 10))
b = np.ceil(np.random.uniform(0,10,10))

((a+b) * (-a/2))

array([-48. , -20. , -85.5,  -4.5, -65. , -28. , -39. , -16.5, -68. ,
       -27.5])

In [75]:
np.add(a, b, out=b)

array([16.,  8., 19.,  9., 13.,  8., 13., 11., 17., 11.])

In [79]:
np.divide(a, 2, out = a)
np.negative(a, out = a)
np.multiply(a, b, out = a)

array([-48. , -20. , -85.5,  -4.5, -65. , -28. , -39. , -16.5, -68. ,
       -27.5])

In [74]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [96]:
# Needed hint for astype and trunc
a = np.random.uniform(1, 10, 10)
print(a)
print(a // 1)
print(np.floor(a))
print(a - a % 1)
print(a.astype(int))
print(np.trunc(a))

[6.20383348 5.52780467 1.309815   9.5943012  9.6212314  5.97110313
 9.78329661 5.23346828 6.33193939 9.08176296]
[6. 5. 1. 9. 9. 5. 9. 5. 6. 9.]
[6. 5. 1. 9. 9. 5. 9. 5. 6. 9.]
[6. 5. 1. 9. 9. 5. 9. 5. 6. 9.]
[6 5 1 9 9 5 9 5 6 9]
[6. 5. 1. 9. 9. 5. 9. 5. 6. 9.]


In [87]:
hint(36)

hint: %, np.floor, astype, np.trunc


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [99]:
# Was able to do without hint, but confused at their solution...seems overengineered
np.random.randint(0, 5, 25).reshape(5,5)

array([[4, 1, 2, 4, 3],
       [1, 0, 2, 3, 4],
       [0, 1, 0, 0, 1],
       [0, 1, 1, 2, 4],
       [2, 1, 0, 0, 3]])

In [100]:
answer(37)

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


In [101]:
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [110]:
# Needed answer to get fromiter function, and understand it was asking to pull from a generator
def generate():
    for x in range(10):
        yield x
        
a = np.fromiter(generate(), dtype=int, count=-1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [104]:
answer(38)

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [116]:
# Needed answer for linspace function...generates numbers from one value to another evenly spaced. Take [1:] and you'll exclude starting value
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [114]:
answer(39)

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [118]:
# Needed nothing, can also call .sort()
np.sort(np.random.random(10))

array([0.07391223, 0.26816722, 0.37900087, 0.40098381, 0.46764851,
       0.51234794, 0.5363786 , 0.69069124, 0.88733012, 0.96324486])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [125]:
# Needed answer to know the .add.reduce paradigm...only works for smaller arrays
a = np.random.random(5)
np.add.reduce(a)

3.8708620445852393

In [124]:
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [129]:
# Had the .equal, but that returns a boolean array. Want just a boolean value so...
# allclose -- meant to be used with floats, as very very small differences (usually precision loss) will not count as unequal
# array_equal -- same as allclose, except they have to be exactly the same, meant to be used with ints
a = np.random.random(5)
b = np.random.random(5)

print(np.equal(a,b))
print(np.allclose(a,b))
print(np.array_equal(a,b))

[False False False False False]
False
False


In [128]:
answer(42)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [131]:
# Needed answer to understand .flags.writeable
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [143]:
# Needed to look up formula, then answer for the correct slicing and np.arctan2
a = np.random.randint(0, 10, 20).reshape(10,2)
X, Y = a[:,0], a[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[10.63014581  8.60232527  9.89949494  9.21954446  7.81024968  7.21110255
  9.8488578   7.21110255  3.         12.04159458]
[0.85196633 0.95054684 0.78539816 0.21866895 0.87605805 0.5880026
 1.152572   0.98279372 0.         0.84415399]


In [140]:
answer(44)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [148]:
# Needed hint for argmax
a = np.random.random(10)
a[np.argmax(a)] = 0
print(a)

[0.4181966  0.14995245 0.0046121  0.72036899 0.75384886 0.62446441
 0.8970497  0.         0.64659656 0.90693606]


In [149]:
answer(45)

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [159]:
# Needed answer for entire construction. Custom datatype, meshgrid with linspace
a = np.zeros((5,5), [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [155]:
print(a)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]


In [153]:
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)